version: "3.3"

services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.${DOMAIN}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${DOMAIN}:8080';
        gitlab_rails['lfs_enabled'] = true;
    ports:
      - "8080:80"
      - "8443:443"
      - "2224:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config: $GITLAB_HOME/config
  gitlab_logs: $GITLAB_HOME/logs
  gitlab_data: $GITLAB_HOME/data